import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F4F7F7" },
  authSafeArea: { flex: 1, backgroundColor: "#071A2B" },
  authContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 58,
    paddingBottom: 28,
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
  },
  brandMark: {
    width: 54,
    height: 54,
    borderRadius: 17,
    backgroundColor: "#0F6B72",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  brandMarkText: { color: "#E6BF63", fontSize: 17, fontWeight: "800" },
  authEyebrow: {
    color: "#E6BF63",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    marginBottom: 10,
  },
  authTitle: {
    color: "#FFFFFF",
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
  },
  authSubtitle: {
    color: "#B7C5CF",
    fontSize: 15,
    marginTop: 8,
    marginBottom: 30,
  },
  authForm: { gap: 12, width: "100%" },
  authInput: {
    height: 54,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#294256",
    backgroundColor: "#102A3D",
    color: "#FFFFFF",
    paddingHorizontal: 16,
    fontSize: 15,
  },
  authInputWrap: {
    height: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#294256",
    backgroundColor: "#102A3D",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authInputField: { flex: 1, color: "#FFFFFF", fontSize: 15 },
  authNotice: { color: "#E6BF63", fontSize: 13, marginTop: -2 },
  authError: { color: "#FCA5A5", fontSize: 13, marginTop: -2 },
  authDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 4,
  },
  authDividerLine: { flex: 1, height: 1, backgroundColor: "#294256" },
  authDividerText: { color: "#8EA0AD", fontSize: 12 },
  socialButton: {
    height: 52,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#294256",
    backgroundColor: "#102A3D",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  facebookButton: { backgroundColor: "#1877F2", borderColor: "#1877F2" },
  googleMark: { color: "#4285F4", fontSize: 18, fontWeight: "800" },
  facebookMark: { color: "#FFFFFF", fontSize: 22, fontWeight: "800" },
  socialButtonText: { color: "#E9F0F3", fontSize: 14, fontWeight: "700" },
  facebookButtonText: { color: "#FFFFFF" },
  authSwitch: { alignItems: "center", marginTop: 22 },
  authSwitchText: { color: "#B7C5CF", fontSize: 14 },
  authSwitchAction: { color: "#E6BF63", fontWeight: "800" },
  primaryButton: {
    alignItems: "center",
    justifyContent: "center",
    height: 54,
    borderRadius: 15,
    backgroundColor: "#0F6B72",
    marginTop: 8,
  },
  primaryButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
  buttonPressed: { opacity: 0.88, transform: [{ scale: 0.98 }] },
  sessionLoading: { flex: 1, alignItems: "center", justifyContent: "center" },
  sessionLoadingText: { color: "#6B7280", fontSize: 14, marginTop: 14 },
  listContent: { paddingHorizontal: 20, paddingBottom: 32 },
  header: {
    paddingTop: 24,
    paddingBottom: 25,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  homeBanner: {
    width: "100%",
    height: 96,
    borderRadius: 18,
    marginBottom: 18,
    backgroundColor: "#DBEAFE",
  },
  eyebrow: {
    color: "#3B82F6",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.5,
    marginBottom: 9,
  },
  heading: {
    color: "#111827",
    fontSize: 34,
    lineHeight: 39,
    fontWeight: "800",
  },
  subheading: { color: "#78817C", fontSize: 15, marginTop: 7 },
  profileCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#DCECE8",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 3,
  },
  profileText: { color: "#0F6B72", fontSize: 13, fontWeight: "800" },
  searchBox: {
    height: 53,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    elevation: 2,
  },
  searchIcon: { marginRight: 11 },
  searchInput: { flex: 1, color: "#111827", fontSize: 15 },
  filtersContent: { paddingVertical: 20, gap: 8 },
  filterChip: {
    borderWidth: 1,
    borderColor: "#DFE5E1",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  selectedFilterChip: { backgroundColor: "#3B82F6", borderColor: "#3B82F6" },
  filterText: { color: "#69736E", fontSize: 13, fontWeight: "600" },
  selectedFilterText: { color: "#FFFFFF" },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 13,
  },
  sectionCaption: { color: "#9CA3AF", fontSize: 12, marginTop: 4 },
  sectionTitle: { color: "#111827", fontSize: 21, fontWeight: "800" },
  resultCount: { color: "#8B948F", fontSize: 13 },
  roomGridRow: { gap: 10, alignItems: "stretch" },
  roomCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#EBEFEC",
    flex: 1,
    maxWidth: "49%",
    elevation: 2,
  },
  roomImage: {
    width: "100%",
    height: 86,
    borderRadius: 13,
    marginBottom: 13,
    backgroundColor: "#DBEAFE",
  },
  pressed: { opacity: 0.75, transform: [{ scale: 0.99 }] },
  cardTopRow: { flexDirection: "row", alignItems: "center" },
  roomIcon: {
    width: 47,
    height: 47,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  roomIconText: { color: "#2563EB", fontSize: 16, fontWeight: "800" },
  roomTitleWrap: { flex: 1 },
  titleLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  roomName: { color: "#1F2937", fontSize: 17, fontWeight: "800" },
  roomMeta: { color: "#818A85", fontSize: 13, marginTop: 5 },
  roomType: { color: "#6B7280", fontSize: 12, marginTop: 13 },
  cardStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 15,
  },
  capacityText: { color: "#6B7280", fontSize: 11, fontWeight: "700" },
  capacityWrap: { flexDirection: "row", alignItems: "center", gap: 4 },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  availablePill: { backgroundColor: "#ECFDF5" },
  busyPill: { backgroundColor: "#FFF2DF" },
  statusDot: { width: 6, height: 6, borderRadius: 3, marginRight: 5 },
  availableDot: { backgroundColor: "#4B9B68" },
  busyDot: { backgroundColor: "#D98B36" },
  statusText: { fontSize: 11, fontWeight: "700" },
  availableText: { color: "#047857" },
  busyText: { color: "#B36B21" },
  facilityRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 12,
    flexWrap: "wrap",
  },
  facilityTag: {
    backgroundColor: "#F4F6F4",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  facilityText: { color: "#7C8780", fontSize: 11 },
  nextSlot: {
    color: "#2563EB",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 14,
  },
  nextSlotBusy: { color: "#BB7A31" },
  emptyState: { alignItems: "center", paddingVertical: 50 },
  emptyTitle: { color: "#27362E", fontSize: 18, fontWeight: "800" },
  emptyText: { color: "#8A948E", fontSize: 14, marginTop: 7 },
  roomSkeleton: {
    height: 142,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 13,
    padding: 16,
    flexDirection: "row",
  },
  skeletonIcon: {
    width: 47,
    height: 47,
    borderRadius: 14,
    backgroundColor: "#E5E7EB",
  },
  skeletonLines: { flex: 1, paddingLeft: 13, paddingTop: 4 },
  skeletonLineLong: {
    width: "62%",
    height: 14,
    borderRadius: 7,
    backgroundColor: "#E5E7EB",
  },
  skeletonLineShort: {
    width: "42%",
    height: 10,
    borderRadius: 5,
    backgroundColor: "#F3F4F6",
    marginTop: 10,
  },
  skeletonFooter: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#F3F4F6",
  },
  detailContent: { padding: 20, paddingBottom: 40 },
  backButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    justifyContent: "center",
    marginBottom: 10,
  },
  backLink: {
    color: "#2563EB",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 25,
  },
  detailHero: { alignItems: "center", paddingBottom: 28 },
  detailRoomImage: {
    width: "100%",
    maxWidth: 460,
    height: 190,
    borderRadius: 22,
    marginBottom: 18,
    backgroundColor: "#DBEAFE",
  },
  detailRoomName: { color: "#111827", fontSize: 30, fontWeight: "800" },
  detailStatus: { marginTop: 13 },
  detailSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 17,
    padding: 17,
    marginBottom: 13,
    borderWidth: 1,
    borderColor: "#EBEFEC",
  },
  detailLabel: {
    color: "#1F2937",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 15,
  },
  infoGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 17 },
  infoItem: { width: "50%" },
  infoLabel: { color: "#8B948F", fontSize: 12, marginBottom: 5 },
  infoValue: { color: "#374151", fontSize: 14, fontWeight: "700" },
  description: { color: "#6F7B74", fontSize: 14, lineHeight: 21 },
  disabledButton: { backgroundColor: "#B8C1BB" },
  bookingContent: { padding: 20, paddingBottom: 40 },
  calendarCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 10,
    marginBottom: 26,
    width: "100%",
    maxWidth: 340,
    alignSelf: "center",
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 17,
  },
  calendarTitle: { color: "#111827", fontSize: 15, fontWeight: "800" },
  calendarArrow: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  calendarArrowText: { color: "#2563EB", fontSize: 24, lineHeight: 26 },
  weekRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 8,
  },
  weekDay: {
    width: "14.28%",
    textAlign: "center",
    color: "#9CA3AF",
    fontSize: 11,
    fontWeight: "800",
  },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarDay: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  calendarDaySelected: { backgroundColor: "#3B82F6" },
  calendarDayText: { color: "#374151", fontSize: 13, fontWeight: "600" },
  calendarDaySelectedText: { color: "#FFFFFF", fontWeight: "800" },
  bookingTitle: {
    color: "#111827",
    fontSize: 30,
    fontWeight: "800",
    marginBottom: 3,
  },
  slotGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginBottom: 26,
  },
  slotOption: {
    width: "48%",
    minHeight: 64,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#DFE5E1",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    paddingHorizontal: 13,
  },
  selectedOption: { backgroundColor: "#3B82F6", borderColor: "#3B82F6" },
  optionText: {
    color: "#5D6B62",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  selectedOptionText: { color: "#FFFFFF" },
  slotStatus: { color: "#2563EB", fontSize: 11, marginTop: 5 },
  bookedSlot: { backgroundColor: "#F3F4F6", borderColor: "#E5E7EB" },
  bookedSlotText: { color: "#9CA3AF" },
  bookingSummary: {
    backgroundColor: "#EFF6FF",
    borderRadius: 15,
    padding: 16,
    marginBottom: 15,
  },
  summaryLabel: {
    color: "#2563EB",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  summaryRoom: {
    color: "#1F2937",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 8,
  },
  summarySlot: { color: "#6B7280", fontSize: 13, marginTop: 4 },
  profileContent: { padding: 20, paddingBottom: 36 },
  profilePageTitle: { color: "#082238", fontSize: 30, fontWeight: "800" },
  profileHero: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#082238",
    borderRadius: 20,
    padding: 20,
    marginTop: 22,
    marginBottom: 14,
  },
  profileAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#0F6B72",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  profileAvatarText: { color: "#E6BF63", fontSize: 18, fontWeight: "800" },
  profileAvatarButton: { alignItems: "center", marginRight: 14, position: "relative" },
  profileAvatarImage: { width: 58, height: 58, borderRadius: 29 },
  avatarEditBadge: {
    position: "absolute",
    right: 3,
    top: 38,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#E6BF63",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEditText: { color: "#E6BF63", fontSize: 11, fontWeight: "700", marginTop: 4 },
  profileIdentity: { flex: 1 },
  profileInput: {
    height: 48,
    borderWidth: 1,
    borderColor: "#C5D2D2",
    borderRadius: 10,
    paddingHorizontal: 12,
    color: "#082238",
    marginTop: 12,
  },
  profileActionButton: { alignSelf: "flex-start", marginTop: 12 },
  profileActionText: { color: "#0F6B72", fontSize: 14, fontWeight: "800" },
  profileName: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" },
  profileEmail: { color: "#B7C5CF", fontSize: 12, marginTop: 5 },
  profileSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 17,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#D8E2E1",
  },
  profileSectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  preferenceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  preferenceLabel: { color: "#4B5563", fontSize: 14 },
  preferenceValue: { color: "#0F6B72", fontSize: 14, fontWeight: "700" },
  logoutButton: {
    alignItems: "center",
    justifyContent: "center",
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D9B85A",
    backgroundColor: "#FFFFFF",
    marginTop: 2,
    flexDirection: "row",
    gap: 8,
  },
  logoutText: { color: "#0F6B72", fontSize: 15, fontWeight: "800" },
  bookingList: { padding: 20, paddingBottom: 32 },
  bookingListTitle: { color: "#111827", fontSize: 30, fontWeight: "800" },
  bookingCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 17,
    padding: 17,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#EBEFEC",
  },
  bookingCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bookingCardRoom: { color: "#1F2937", fontSize: 18, fontWeight: "800" },
  bookingStatus: {
    color: "#047857",
    backgroundColor: "#ECFDF5",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "700",
  },
  cancelledStatus: { color: "#A06A36", backgroundColor: "#FFF2DF" },
  bookingCardDate: { color: "#66736B", fontSize: 14, marginTop: 14 },
  bookingCardTime: {
    color: "#1F2937",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 5,
  },
  cancelButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FFF7F7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    marginTop: 14,
  },
  cancelButtonText: { color: "#B36B21", fontSize: 13, fontWeight: "700" },
  emptyBooking: { alignItems: "center", paddingTop: 70 },
  tabIcon: { fontSize: 20, fontWeight: "800", lineHeight: 22 },
});
